#!/usr/bin/env python3
"""Validate pipeline artifacts before deployment.

Replaces the validate-artifacts Copilot skill with deterministic checks.
Exit code 0 = all checks pass, 1 = one or more failures.
"""

import json
import os
import re
import sys
from datetime import datetime, timedelta, timezone

ROOT = os.path.join(os.path.dirname(__file__), "..")
PAPERS_PATH = os.path.join(ROOT, "data", "papers.json")
ANALYSIS_PATH = os.path.join(ROOT, "data", "analysis.json")
HTML_PATH = os.path.join(ROOT, "docs", "index.html")

REQUIRED_PAPER_FIELDS = {"id", "title", "authors", "published_date", "abstract", "pdf_link", "categories"}
REQUIRED_ANALYSIS_EXTRA = {"tldr", "keywords", "relevance_score"}

failures: list[str] = []


def fail(msg: str) -> None:
    failures.append(msg)
    print(f"  FAIL: {msg}", file=sys.stderr)


def check_json_file(path: str, label: str) -> list | None:
    if not os.path.isfile(path):
        fail(f"{label}: file does not exist")
        return None
    if os.path.getsize(path) == 0:
        fail(f"{label}: file is empty")
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        fail(f"{label}: invalid JSON — {e}")
        return None
    if not isinstance(data, list):
        fail(f"{label}: top-level value is not an array")
        return None
    return data


def validate_papers(data: list) -> None:
    cutoff = datetime.now(timezone.utc) - timedelta(days=4)
    for i, paper in enumerate(data):
        missing = REQUIRED_PAPER_FIELDS - set(paper.keys())
        if missing:
            fail(f"papers[{i}]: missing fields {missing}")
        pub = paper.get("published_date")
        if pub:
            try:
                dt = datetime.fromisoformat(pub.replace("Z", "+00:00"))
                if dt < cutoff:
                    fail(f"papers[{i}]: published_date {pub} is older than 4 days")
            except ValueError:
                fail(f"papers[{i}]: published_date is not valid ISO 8601")


def validate_analysis(data: list, papers_len: int) -> None:
    if len(data) != papers_len:
        fail(f"analysis.json length ({len(data)}) != papers.json length ({papers_len})")

    prev_score = float("inf")
    for i, entry in enumerate(data):
        missing = (REQUIRED_PAPER_FIELDS | REQUIRED_ANALYSIS_EXTRA) - set(entry.keys())
        if missing:
            fail(f"analysis[{i}]: missing fields {missing}")

        score = entry.get("relevance_score")
        if not isinstance(score, int) or not (0 <= score <= 10):
            fail(f"analysis[{i}]: relevance_score {score!r} is not an integer 0-10")
        else:
            if score > prev_score:
                fail(f"analysis[{i}]: not sorted by relevance_score descending ({score} > {prev_score})")
            prev_score = score

        kw = entry.get("keywords")
        if not isinstance(kw, list) or len(kw) > 5:
            fail(f"analysis[{i}]: keywords must be an array of at most 5 strings")


def validate_html(papers_len: int) -> None:
    if not os.path.isfile(HTML_PATH):
        fail("docs/index.html: file does not exist")
        return
    with open(HTML_PATH, "r", encoding="utf-8") as f:
        html = f.read()
    if not html.strip():
        fail("docs/index.html: file is empty")
        return
    if "<!DOCTYPE html>" not in html[:100]:
        fail("docs/index.html: missing <!DOCTYPE html>")
    if not re.search(r"<title>.*?</title>", html, re.DOTALL):
        fail("docs/index.html: missing <title> element")

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    if today not in html:
        fail(f"docs/index.html: today's date ({today}) not found in header")

    count_match = re.search(r"(\d+)\s*papers?\s*reviewed", html)
    if count_match:
        html_count = int(count_match.group(1))
        if html_count != papers_len:
            fail(f"docs/index.html: paper count ({html_count}) != analysis.json length ({papers_len})")

    if "Generated by Q-Bio Watchtower" not in html:
        fail("docs/index.html: missing footer text 'Generated by Q-Bio Watchtower'")


def main() -> None:
    print("[validate] Checking data/papers.json...")
    papers = check_json_file(PAPERS_PATH, "data/papers.json")
    if papers is not None:
        validate_papers(papers)

    print("[validate] Checking data/analysis.json...")
    analysis = check_json_file(ANALYSIS_PATH, "data/analysis.json")
    if analysis is not None:
        validate_analysis(analysis, len(papers) if papers is not None else 0)

    print("[validate] Checking docs/index.html...")
    validate_html(len(analysis) if analysis is not None else 0)

    if failures:
        print(f"\n[validate] {len(failures)} check(s) FAILED:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        sys.exit(1)
    else:
        print("[validate] All checks PASSED.")
        sys.exit(0)


if __name__ == "__main__":
    main()
